apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: worq-todo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: worq-todo-app-backend:latest
        imagePullPolicy: Never # For local images
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MONGO_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 